{{- if .Values.alerts.enabled -}}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  creationTimestamp: null
  labels:
    alertmanagerconfig.kubegems.io/name: {{ template "prometheus-mongodb-exporter.fullname" . }}
    alertmanagerconfig.kubegems.io/type: monitor
  name: {{ template "prometheus-mongodb-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  inhibitRules:
  - equal:
    - instance
    - gems_namespace
    - gems_alertname
    sourceMatch:
    - name: gems_namespace
      value: {{ .Release.Namespace }}
    - name: gems_alertname
      value: MongodbTooManyMemories
    - name: severity
      value: critical
    targetMatch:
    - name: gems_namespace
      value: {{ .Release.Namespace }}
    - name: gems_alertname
      value: MongodbTooManyMemories
    - name: severity
      value: error
  receivers:
  - name: "null"
  - name: kubegems-default-webhook-id-1
    webhookConfigs:
    - httpConfig:
        tlsConfig:
          ca: {}
          cert: {}
          insecureSkipVerify: true
      sendResolved: true
      url: https://kubegems-local-agent.kubegems-local:8041/alert
  route:
    groupBy:
    - gems_namespace
    - gems_alertname
    groupInterval: 30s
    groupWait: 30s
    receiver: "null"
    routes:
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: MongodbDown
      receiver: kubegems-default-webhook-id-1
      repeatInterval: 10m
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: MongodbTooManyConnections
      receiver: kubegems-default-webhook-id-1
      repeatInterval: 10m
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: MongodbLowAvalibleConnections
      receiver: kubegems-default-webhook-id-1
      repeatInterval: 10m
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: MongodbTooManyMemories
      receiver: kubegems-default-webhook-id-1
      repeatInterval: 10m
{{- end }}