{{- if .Values.alerts.enabled -}}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  creationTimestamp: null
  labels:
    alertmanagerconfig.kubegems.io/name: {{ template "prometheus-rabbitmq-exporter.fullname" . }}
    alertmanagerconfig.kubegems.io/type: monitor
  name: {{ template "prometheus-rabbitmq-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  receivers:
  - name: "null"
  - name: kubegems-default-webhook-id-1
    webhookConfigs:
    - httpConfig:
        tlsConfig:
          ca: {}
          cert: {}
          insecureSkipVerify: true
      sendResolved: true
      url: https://kubegems-local-agent.kubegems-local:8041/alert
  route:
    groupBy:
    - gems_namespace
    - gems_alertname
    groupInterval: 30s
    groupWait: 30s
    receiver: "null"
    routes:
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: RabbitmqNodeDown
      receiver: kubegems-default-webhook-id-1
      repeatInterval: 10m
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: RabbitmqClusterDown
      receiver: kubegems-default-webhook-id-1
      repeatInterval: 10m
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: RabbitMQClusterPartition
      receiver: kubegems-default-webhook-id-1
      repeatInterval: 10m
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: RabbitmqOutOfMemory
      receiver: kubegems-default-webhook-id-1
      repeatInterval: 10m
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: RabbitmqTooManyConnections
      receiver: kubegems-default-webhook-id-1
      repeatInterval: 10m
{{- end }}