# Default values for jmx-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.cn-beijing.aliyuncs.com/kubegemsapp/jmx-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.17.0"

host: jmx-remote-host:2111

auth:
  enabled: false
  username: jmx-user
  password: cloud1688

#A list of rules to apply in order, processing stops at the first matching rule. 
#Attributes that aren't matched aren't collected. If not specified, defaults to collecting everything in the default format.
filter:
  - pattern: "java.*"
  - pattern: "jmx.*"

nameOverride: "jmx-exporter"
fullnameOverride: "jmx-exporter"

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 50m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: true
  #  namespace: monitoring
  labels: {}
  interval: 60s
  scrapeTimeout: 10s
  scheme: http
  path: /metrics
  relabelings: []
  targetLabels: []
  metricRelabelings: []
  sampleLimit: 0

alerts:
  enabled: false
  rules: []
  #- alert: cassandra_failing_or_dead_nodes
  #  expr: |
  #    kube_statefulset_replicas{namespace="{{ .Release.Namespace }}",statefulset="{{ include "prometheus-cassandra-exporter.fullname" . }}"}
  #    - kube_statefulset_status_replicas{namespace="{{ .Release.Namespace }}",statefulset="{{ include "prometheus-cassandra-exporter.fullname" . }}"}
  #    != 0
  #  for: 5m
  #  labels:
  #    severity: critical
  #  annotations:
  #    description: The service of cassandra is not available.
