{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-cassandra-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "prometheus-cassandra-exporter.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}    
spec:
  selector:
    matchLabels: 
      {{- include "prometheus-cassandra-exporter.labels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port | default "metrics" }}
      {{- if .Values.serviceMonitor.interval}}
      interval: {{ .Values.serviceMonitor.interval | default "60s" }}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | default "10s" }}
      scheme: {{ .Values.serviceMonitor.scheme | default "http" }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings:
      {{- toYaml .Values.serviceMonitor.relabelings | nindent 4 }}
      {{- end }}
      {{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
      {{ toYaml .Values.serviceMonitor.metricRelabelings | nindent 4 }}
      {{- end }}
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
